feat: initial implementation
storacha/dag.w3s.link pull request #2
Opened 2023-06-07 13:34 UTC by alanshaw

This is a worker for dag.w3s.link that proxies to freeway. It restricts it's usage to the graph API and checks root CIDs against the denylist API before allowing access.

2023-06-07 17:07 UTC, vasco-santos requested changes
Cool 🙌🏼 

Can we add github workflows and README for it?

2023-06-07 17:08 UTC, alanshaw commented
> Can we add github workflows and README for it?

In main already!

2023-06-07 17:16 UTC, vasco-santos commented
> In main already!

Gotcha, tests even ran but I did not notice

2023-06-08 10:44 UTC, vasco-santos approved these changes
LGTM

2023-06-08 10:50 UTC, merged